module.exports={
    chainWebpack:config=>{
      //删除编译后的独立js文件上的预获取操作
      config.plugins.delete("prefetch")
    }
}
//在new1上的更改
aaaaaaaaaaaaaaaaaa
//在主支
bbbbbbbbbbb
//在主支
ffffffffffffff
//解决
qqqqqqqqqqqqqqqqqq
